[package]
name = "RSqlDB"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "common",
    "parser",
    "planner"
]
resolver = "2"

[workspace.dependencies]
anyhow = "*"
derive-new = "*"

[dependencies]

